"""Add bio, age, and hobbies fields to User model

Revision ID: 3f35347e0a5f
Revises: 97b0c3db9e48
Create Date: 2025-05-13 11:20:51.558827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f35347e0a5f'
down_revision: Union[str, None] = '97b0c3db9e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hobbies', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hobbies')
    op.drop_column('users', 'age')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
